version: "2"
services:
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    links:
     - influxdb
  influxdb:
    image: tutum/influxdb 
    stdin_open: true
    tty: true
    volumes:
     - /var/influxdb:/data
    ports:
     - "8083:8083"
     - "8086:8086"
    hostname: influxdb
    environment:
     PRE_CREATE_DB: grafanademo
     INFLUXDB_USER: admin
     INFLUXDB_PASS: admin

